"""empty message

Revision ID: 2fb81b0b28d4
Revises: 38e3f848666b
Create Date: 2021-04-30 17:03:19.945674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb81b0b28d4'
down_revision = '38e3f848666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joinedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joinedAt')
    # ### end Alembic commands ###
