"""empty message

Revision ID: a4b015e1c4d7
Revises: 2fb81b0b28d4
Create Date: 2021-05-05 20:11:58.272579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b015e1c4d7'
down_revision = '2fb81b0b28d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('KeyHighScore', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('noteHighScore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'noteHighScore')
    op.drop_column('users', 'KeyHighScore')
    # ### end Alembic commands ###
